name: Deploy to gh-pages
on: 
  push:
    branches:
      - main
jobs:
  deploy-valheim-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
        with:
          ref: 'main'

      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v1
        with:
          ref: 'gh-pages'
          clean: false
      
      - name: commit index changes
        run: |
          git add index.yaml
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name addyvan
          git commit -m "release $version" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: gh-pages
